name: Update LeetCode Problem Count

on:
  push:
    paths:
      - '**/*.py'
      - '**/README.md'
      - '**/*-*/'
  workflow_dispatch: {}

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run update_readme.py
        run: |
          python scripts/update_readme.py

      - name: Commit and push if README changed
        run: |
          git config --global user.name "LeetCode Bot"
          git config --global user.email "leetcode-bot@example.com"

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add README.md
            git commit -m "Update solved problem count"
            git push
          fi

      - name: Done
        run: echo " README solved count done"
